// Temporary flat config generated by SunLint
import customPlugin from 'D:\toturial_nestjs_review\node_modules\@sun-asterisk\sunlint\integrations\eslint\plugin\index.js';

export default [
  {
  "files": [
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
  ],
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    }
  },
  "plugins": { "custom": customPlugin },
    "rules": {
    "custom/typescript_s041": "warn",
    "custom/typescript_s042": "warn",
    "custom/typescript_s043": "warn",
    "custom/typescript_s044": "warn",
    "custom/typescript_s045": "warn",
    "custom/typescript_s046": "warn",
    "custom/typescript_s047": "warn",
    "custom/typescript_s050": "warn"
  }
},
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { "custom": customPlugin },
    languageOptions: {
      parser: (await import('@typescript-eslint/parser')).default,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      }
    },
    rules: {
  "custom/typescript_s041": "warn",
  "custom/typescript_s042": "warn",
  "custom/typescript_s043": "warn",
  "custom/typescript_s044": "warn",
  "custom/typescript_s045": "warn",
  "custom/typescript_s046": "warn",
  "custom/typescript_s047": "warn",
  "custom/typescript_s050": "warn"
}
  }
];
